### ISSUE TITLE
Multiple go routines, results in IO Wait deadlock

### ISSUE THREAD

**Issue by sebastianwestberg** [cretz/bine#45]
First of all, thank you for Bine! I love it so far and I'm using it to learn more Go.

Anyway, I stumble upon a problem when using the dialer in multiple routines. Sometimes I can run it for a long period without any issues. I wonder if you might have any idea what's going wrong.

I'm setting up the dialer once in main.go and provide each worker with it.

```
goroutine 820 [select]:
github.com/cretz/bine/tor.(*Dialer).DialContext(0xc000101270, 0x4716ce0, 0xc00010a000, 0x469fdc7, 0x3, 0xc000422730, 0x42, 0x60, 0x4c3a4a0, 0x118, ...)
        /Users/sebwes/src/go/pkg/mod/github.com/cretz/bine@v0.1.1-0.20200124154328-f9f678b84cca/tor/dialer.go:107 +0x1ea
net/http.(*Transport).dial(0xc000156a00, 0x4716ce0, 0xc00010a000, 0x469fdc7, 0x3, 0xc000422730, 0x42, 0x0, 0xc00011c500, 0x0, ...)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/transport.go:1141 +0x1fd
net/http.(*Transport).dialConn(0xc000156a00, 0x4716ce0, 0xc00010a000, 0x0, 0xc0005fe5f0, 0x5, 0xc000422730, 0x42, 0x0, 0xc000217560, ...)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/transport.go:1575 +0x1abb
net/http.(*Transport).dialConnFor(0xc000156a00, 0xc000394840)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/transport.go:1421 +0xc6
created by net/http.(*Transport).queueForDial
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/transport.go:1390 +0x40f

goroutine 821 [IO wait]:
internal/poll.runtime_pollWait(0xb491660, 0x72, 0x4711680)
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000ddb98, 0x72, 0x4711600, 0x49a0f90, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/Cellar/go/1.15.5/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000ddb80, 0xc0002da750, 0x4, 0x90, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0000ddb80, 0xc0002da750, 0x4, 0x90, 0x45, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000d4220, 0xc0002da750, 0x4, 0x90, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/net.go:182 +0x8e
io.ReadAtLeast(0xb4180d8, 0xc0000d4220, 0xc0002da750, 0x4, 0x90, 0x4, 0x0, 0x90, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/Cellar/go/1.15.5/libexec/src/io/io.go:333
golang.org/x/net/internal/socks.(*Dialer).connect(0xc0001227d0, 0x4716ce0, 0xc00010a000, 0x4718e20, 0xc0000d4220, 0xc000422730, 0x42, 0x0, 0x0, 0x0, ...)
        /Users/sebwes/src/go/pkg/mod/golang.org/x/net@v0.0.0-20201110031124-69a78807bb2b/internal/socks/client.go:109 +0x738
golang.org/x/net/internal/socks.(*Dialer).DialWithConn(0xc0001227d0, 0x4716ce0, 0xc00010a000, 0x4718e20, 0xc0000d4220, 0x469fdc7, 0x3, 0xc000422730, 0x42, 0x0, ...)
        /Users/sebwes/src/go/pkg/mod/golang.org/x/net@v0.0.0-20201110031124-69a78807bb2b/internal/socks/socks.go:196 +0xec
golang.org/x/net/internal/socks.(*Dialer).Dial(0xc0001227d0, 0x469fdc7, 0x3, 0xc000422730, 0x42, 0x100000000000000, 0x0, 0x0, 0x0)
        /Users/sebwes/src/go/pkg/mod/golang.org/x/net@v0.0.0-20201110031124-69a78807bb2b/internal/socks/socks.go:226 +0x396
github.com/cretz/bine/tor.(*Dialer).DialContext.func1(0xc000101270, 0x469fdc7, 0x3, 0xc000422730, 0x42, 0xc0006a48a0, 0x4716ce0, 0xc00010a000, 0xc0006a4900)
        /Users/sebwes/src/go/pkg/mod/github.com/cretz/bine@v0.1.1-0.20200124154328-f9f678b84cca/tor/dialer.go:99 +0x7b
created by github.com/cretz/bine/tor.(*Dialer).DialContext
        /Users/sebwes/src/go/pkg/mod/github.com/cretz/bine@v0.1.1-0.20200124154328-f9f678b84cca/tor/dialer.go:98 +0xfa
```

Happy for any input :)

**Comment by cretz** [comment]
Hrmm, off the top of my head I can't think of anything. It looks like it's hanging at https://github.com/golang/net/blob/69a78807bb2bb6d1599c68698c6b009505012083/internal/socks/client.go#L109 which makes me think it's Tor that's holding it up. Might need to check some kind of max connection config in Tor, or otherwise enable some kind of debugging on that side. I don't see any issues on the Go side causing the read to hang.

**Comment by sebastianwestberg** [comment]
Thanks for the help. This way totally my fault and had nothing to do with bine or the Tor client! Closing :)

**Comment by unusualevent** [comment]
@cretz how would you configure the connection config in the embedded Tor?

**Comment by cretz** [comment]
Does not seem related to the issue you're commenting on here and I am not sure what you mean by connection config.
